### ISSUE TITLE
Pick a license

### ISSUE THREAD

**Issue by linkmauve** [Ace314159/NDS-Emulator#1]
Hi, I’ve just discovered your emulator, despite its young age it seems to already handle quite a few games and that’s great!

Before contributing though, I’d like you to decide on a license, free software if possible. As it currently stands, that makes it hard to contribute.

Depending on the kind of usages you want to allow, I may be able to recommend you a license if you’re interested.

**Comment by Ace314159** [comment]
Thanks for the kinds words about my emulator! I haven't thought of putting a license yet since I never thought anyone would contribute haha.

I was thinking of using something like GPL since I'm fine with others doing whatever they want with my code as long as it's open source. Is that understanding accurate? Do you have any other suggestions?

**Comment by linkmauve** [comment]
I’m perfectly happy with the GPL, additionally it’ll let us potentially share code (or at least look at it) with DeSmuME and melonDS if the need arises. :)

That was the one I was gonna suggest btw. ^^
